### ISSUE TITLE
可拖拽可調整大小的 Player

### ISSUE THREAD

**Issue by antfu** [maru-re/maru#32]
理論上設想的情況是在桌面 layout 下，player 的位置和大小都可以調整（可磁吸式保持貼邊），由此可以輕易讓出更多空間給歌詞，或是調換影片和歌詞的位置等

**Comment by oliver139** [comment]
拖拽我之前實現了
調整大小我之前也有想過做
我之後有空再研究看看磁吸的做法🤔

**Comment by oliver139** [comment]
Will try to implement using
https://www.npmjs.com/package/vue-draggable-resizable
