### ISSUE TITLE
切换屏幕断点闪烁

### ISSUE THREAD

**Issue by zyyv** [maru-re/maru#64]
https://github.com/user-attachments/assets/b2b63735-7b49-4658-a04c-423047221ae3

https://github.com/maru-re/maru/blob/7b0af12935a0cdefb8ab3dba3037c429bbebd3e7/app/state/breakpoints.ts#L3-L6

使用 js 判断会有闪烁的问题，是否愿意改进用 css 针对屏幕大小进行布局

```ts
// uno.config.ts
{
  breakpoints: {
    md: '768px', // mobile
    lg: '1024px', // tablet
  }
}
```

**Comment by antfu** [comment]
可是有些東西好像不太好用 css 做，有什麼提案麼？

**Comment by zyyv** [comment]
我自己先在本地尝试下用css好解决啵～如果可以我会尝试 pr
