### ISSUE TITLE
【建议】chatgpt辅助部分主要问题是gpt容易漏标，可以先用pykakasi等库先生成一个格式正确但有错误的再让gpt订正

### ISSUE THREAD

**Issue by theSlowBird** [maru-re/maru#87]
原始方案使用“影色舞”测试，漏31处（约1/3），反向注汉字1处，擅自分段一处，错误1处。

新方案使用“春日影”测试，错误2个字，共3处（{縁}(えにし)を1处、{頬}(ほお)を2处）。
使用“影色舞”测试，错误2个字，共3处（{一}(いち)1处、{称}(とな)えて2处），擅自分段2处。

显然新方案是可用级别了。

pykakasi是python的一个库，是非智能的无法正确处理多音字，我可以提供该部分python代码实现。

**Comment by antfu** [comment]
We don't have a Python integration, especially because this app does not have a server integrated. That ChatGPT part is more like a good-to-have addition. Maybe we could have a short script in JavaScript to verify the result from ChatGPT maybe?

**Comment by theSlowBird** [comment]
> We don't have a Python integration, especially because this app does not have a server integrated. That ChatGPT part is more like a good-to-have addition. Maybe we could have a short script in JavaScript to verify the result from ChatGPT maybe?

我发现了一个很简单的js函数就能处理gpt漏标的问题（错误率不变），只要提前给汉字加上{汉字}()这样的空括号，gpt就不会漏标。以下是我使用的js函数：
```
/**
 * 为LRC歌词中的汉字添加 {漢字}() 注释
 * @param {string} lrcContent - 输入的LRC歌词字符串
 * @returns {string} - 处理后的LRC歌词字符串
 */
function annotateKanjiInLRC(lrcContent) {
    // 正则表达式匹配所有单个汉字（Unicode汉字范围）
    const kanjiRegex = /[\u4E00-\u9FFF々]+/g;

    // 替换函数：为每个匹配的汉字添加 {漢字}()
    const annotatedContent = lrcContent.replace(kanjiRegex, (match) => `{${match}}()`);

    return annotatedContent;
}

// 示例输入
const inputLRC = `[00:16.64]交差点の真ん中 急ぐ人に紛れて
[00:21.54]僕だけがあてもなく 漂うみたいだ
[00:26.75]流行りの歌はいつも
[00:29.10]僕のことは歌ってない
[00:31.62]ねえビジョンの中から
[00:33.51]笑いかけないで
[00:36.49]また今日も声にならずに
[00:38.99]飲み込んだ感情
[00:41.52]下書き埋め尽くして
[00:44.36]ああ そうやって何千回夜を越える`;
// 省略其余部分

// 调用函数处理LRC歌词
const outputLRC = annotateKanjiInLRC(inputLRC);

// 输出结果
console.log("处理前的LRC：\n", inputLRC);
console.log("处理后的LRC：\n", outputLRC);
```

只要先把经过annotateKanjiInLRC函数的outputLRC粘贴到你的LRC框里，然后使用你的提示词让gpt填写，就不会出现漏填的现象。

**Comment by antfu** [comment]
Oh nice idea! Do you want to send a quick PR? Thanks!

**Comment by theSlowBird** [comment]
> Oh nice idea! Do you want to send a quick PR? Thanks!

PR已经提交了，测试了没有问题。
